# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bar.ui'
#
# Created: Fri Jul 16 22:05:15 2010
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_BarConfigDialog(object):
    def setupUi(self, BarConfigDialog):
        BarConfigDialog.setObjectName("BarConfigDialog")
        BarConfigDialog.resize(398, 241)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BarConfigDialog.sizePolicy().hasHeightForWidth())
        BarConfigDialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../icons/programIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        BarConfigDialog.setWindowIcon(icon)
        self.verticalLayout_4 = QtGui.QVBoxLayout(BarConfigDialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblFieldToPlot = QtGui.QLabel(BarConfigDialog)
        self.lblFieldToPlot.setObjectName("lblFieldToPlot")
        self.horizontalLayout.addWidget(self.lblFieldToPlot)
        self.cboFieldToPlot = QtGui.QComboBox(BarConfigDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboFieldToPlot.sizePolicy().hasHeightForWidth())
        self.cboFieldToPlot.setSizePolicy(sizePolicy)
        self.cboFieldToPlot.setObjectName("cboFieldToPlot")
        self.horizontalLayout.addWidget(self.cboFieldToPlot)
        self.chkSort = QtGui.QCheckBox(BarConfigDialog)
        self.chkSort.setObjectName("chkSort")
        self.horizontalLayout.addWidget(self.chkSort)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_2 = QtGui.QGroupBox(BarConfigDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lblSampleName1 = QtGui.QLabel(self.groupBox_2)
        self.lblSampleName1.setObjectName("lblSampleName1")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblSampleName1)
        self.txtSampleName1 = QtGui.QLineEdit(self.groupBox_2)
        self.txtSampleName1.setObjectName("txtSampleName1")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.txtSampleName1)
        self.lblSampleName2 = QtGui.QLabel(self.groupBox_2)
        self.lblSampleName2.setObjectName("lblSampleName2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblSampleName2)
        self.txtSampleName2 = QtGui.QLineEdit(self.groupBox_2)
        self.txtSampleName2.setObjectName("txtSampleName2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.txtSampleName2)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(BarConfigDialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.lblFigureWidth = QtGui.QLabel(self.groupBox_3)
        self.lblFigureWidth.setObjectName("lblFigureWidth")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblFigureWidth)
        self.spinFigWidth = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.spinFigWidth.setDecimals(2)
        self.spinFigWidth.setMinimum(2.0)
        self.spinFigWidth.setMaximum(20.0)
        self.spinFigWidth.setSingleStep(0.5)
        self.spinFigWidth.setProperty("value", 8.5)
        self.spinFigWidth.setObjectName("spinFigWidth")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinFigWidth)
        self.lblFigureHeight = QtGui.QLabel(self.groupBox_3)
        self.lblFigureHeight.setObjectName("lblFigureHeight")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblFigureHeight)
        self.spinFigRowHeight = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.spinFigRowHeight.setMinimum(0.1)
        self.spinFigRowHeight.setMaximum(1.0)
        self.spinFigRowHeight.setSingleStep(0.05)
        self.spinFigRowHeight.setProperty("value", 0.25)
        self.spinFigRowHeight.setObjectName("spinFigRowHeight")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinFigRowHeight)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.groupBox = QtGui.QGroupBox(BarConfigDialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.radioLegendPosBest = QtGui.QRadioButton(self.groupBox)
        self.radioLegendPosBest.setChecked(True)
        self.radioLegendPosBest.setObjectName("radioLegendPosBest")
        self.gridLayout.addWidget(self.radioLegendPosBest, 0, 0, 1, 1)
        self.radioLegendPosUpperLeft = QtGui.QRadioButton(self.groupBox)
        self.radioLegendPosUpperLeft.setObjectName("radioLegendPosUpperLeft")
        self.gridLayout.addWidget(self.radioLegendPosUpperLeft, 0, 1, 1, 1)
        self.radioLegendPosCentreLeft = QtGui.QRadioButton(self.groupBox)
        self.radioLegendPosCentreLeft.setObjectName("radioLegendPosCentreLeft")
        self.gridLayout.addWidget(self.radioLegendPosCentreLeft, 0, 2, 1, 1)
        self.radioLegendPosLowerLeft = QtGui.QRadioButton(self.groupBox)
        self.radioLegendPosLowerLeft.setChecked(False)
        self.radioLegendPosLowerLeft.setObjectName("radioLegendPosLowerLeft")
        self.gridLayout.addWidget(self.radioLegendPosLowerLeft, 0, 3, 1, 1)
        self.radioLegendPosUpperRight = QtGui.QRadioButton(self.groupBox)
        self.radioLegendPosUpperRight.setObjectName("radioLegendPosUpperRight")
        self.gridLayout.addWidget(self.radioLegendPosUpperRight, 1, 1, 1, 1)
        self.radioLegendPosCentreRight = QtGui.QRadioButton(self.groupBox)
        self.radioLegendPosCentreRight.setObjectName("radioLegendPosCentreRight")
        self.gridLayout.addWidget(self.radioLegendPosCentreRight, 1, 2, 1, 1)
        self.radioLegendPosLowerRight = QtGui.QRadioButton(self.groupBox)
        self.radioLegendPosLowerRight.setObjectName("radioLegendPosLowerRight")
        self.gridLayout.addWidget(self.radioLegendPosLowerRight, 1, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.buttonBox = QtGui.QDialogButtonBox(BarConfigDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_3.addWidget(self.buttonBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)

        self.retranslateUi(BarConfigDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), BarConfigDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), BarConfigDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(BarConfigDialog)

    def retranslateUi(self, BarConfigDialog):
        BarConfigDialog.setWindowTitle(QtGui.QApplication.translate("BarConfigDialog", "Configure plot", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFieldToPlot.setText(QtGui.QApplication.translate("BarConfigDialog", "Field to plot:", None, QtGui.QApplication.UnicodeUTF8))
        self.chkSort.setText(QtGui.QApplication.translate("BarConfigDialog", "Sort values", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("BarConfigDialog", "Sample names", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSampleName1.setText(QtGui.QApplication.translate("BarConfigDialog", "Sample name 1:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSampleName2.setText(QtGui.QApplication.translate("BarConfigDialog", "Sample name 2:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("BarConfigDialog", "Figure size", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFigureWidth.setText(QtGui.QApplication.translate("BarConfigDialog", "Width:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFigureHeight.setText(QtGui.QApplication.translate("BarConfigDialog", "Row height:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("BarConfigDialog", "Legend position", None, QtGui.QApplication.UnicodeUTF8))
        self.radioLegendPosBest.setText(QtGui.QApplication.translate("BarConfigDialog", "Best", None, QtGui.QApplication.UnicodeUTF8))
        self.radioLegendPosUpperLeft.setText(QtGui.QApplication.translate("BarConfigDialog", "Upper left", None, QtGui.QApplication.UnicodeUTF8))
        self.radioLegendPosCentreLeft.setText(QtGui.QApplication.translate("BarConfigDialog", "Centre left", None, QtGui.QApplication.UnicodeUTF8))
        self.radioLegendPosLowerLeft.setText(QtGui.QApplication.translate("BarConfigDialog", "Lower left", None, QtGui.QApplication.UnicodeUTF8))
        self.radioLegendPosUpperRight.setText(QtGui.QApplication.translate("BarConfigDialog", "Upper right", None, QtGui.QApplication.UnicodeUTF8))
        self.radioLegendPosCentreRight.setText(QtGui.QApplication.translate("BarConfigDialog", "Centre right", None, QtGui.QApplication.UnicodeUTF8))
        self.radioLegendPosLowerRight.setText(QtGui.QApplication.translate("BarConfigDialog", "Lower right", None, QtGui.QApplication.UnicodeUTF8))

