# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'extendedErrorBar.ui'
#
# Created: Fri Jul 16 21:54:53 2010
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ExtendedErrorBarDialog(object):
    def setupUi(self, ExtendedErrorBarDialog):
        ExtendedErrorBarDialog.setObjectName("ExtendedErrorBarDialog")
        ExtendedErrorBarDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        ExtendedErrorBarDialog.resize(337, 279)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ExtendedErrorBarDialog.sizePolicy().hasHeightForWidth())
        ExtendedErrorBarDialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../icons/programIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ExtendedErrorBarDialog.setWindowIcon(icon)
        self.verticalLayout_7 = QtGui.QVBoxLayout(ExtendedErrorBarDialog)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_2 = QtGui.QGroupBox(ExtendedErrorBarDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cboSortingField = QtGui.QComboBox(self.groupBox_2)
        self.cboSortingField.setObjectName("cboSortingField")
        self.cboSortingField.addItem("")
        self.cboSortingField.addItem("")
        self.cboSortingField.addItem("")
        self.horizontalLayout.addWidget(self.cboSortingField)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.groupBox_4 = QtGui.QGroupBox(ExtendedErrorBarDialog)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.chkCorrectedPvalues = QtGui.QCheckBox(self.groupBox_4)
        self.chkCorrectedPvalues.setObjectName("chkCorrectedPvalues")
        self.verticalLayout_3.addWidget(self.chkCorrectedPvalues)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        self.groupBox_3 = QtGui.QGroupBox(ExtendedErrorBarDialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.lblFigureWidth = QtGui.QLabel(self.groupBox_3)
        self.lblFigureWidth.setObjectName("lblFigureWidth")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblFigureWidth)
        self.spinFigWidth = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.spinFigWidth.setDecimals(2)
        self.spinFigWidth.setMinimum(2.0)
        self.spinFigWidth.setMaximum(20.0)
        self.spinFigWidth.setSingleStep(0.5)
        self.spinFigWidth.setProperty("value", 8.5)
        self.spinFigWidth.setObjectName("spinFigWidth")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinFigWidth)
        self.lblFigureHeight = QtGui.QLabel(self.groupBox_3)
        self.lblFigureHeight.setObjectName("lblFigureHeight")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblFigureHeight)
        self.spinFigRowHeight = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.spinFigRowHeight.setMinimum(0.1)
        self.spinFigRowHeight.setMaximum(1.0)
        self.spinFigRowHeight.setSingleStep(0.05)
        self.spinFigRowHeight.setProperty("value", 0.25)
        self.spinFigRowHeight.setObjectName("spinFigRowHeight")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinFigRowHeight)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox = QtGui.QGroupBox(ExtendedErrorBarDialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chkShowSeq = QtGui.QCheckBox(self.groupBox)
        self.chkShowSeq.setObjectName("chkShowSeq")
        self.verticalLayout.addWidget(self.chkShowSeq)
        self.chkPValueLabels = QtGui.QCheckBox(self.groupBox)
        self.chkPValueLabels.setObjectName("chkPValueLabels")
        self.verticalLayout.addWidget(self.chkPValueLabels)
        self.verticalLayout_6.addWidget(self.groupBox)
        self.groupBox_5 = QtGui.QGroupBox(ExtendedErrorBarDialog)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.chkCustomLimits = QtGui.QCheckBox(self.groupBox_5)
        self.chkCustomLimits.setObjectName("chkCustomLimits")
        self.verticalLayout_4.addWidget(self.chkCustomLimits)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtGui.QLabel(self.groupBox_5)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.spinMinimumX = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.spinMinimumX.setMinimum(-1000.0)
        self.spinMinimumX.setMaximum(1000.0)
        self.spinMinimumX.setSingleStep(0.1)
        self.spinMinimumX.setProperty("value", -1.0)
        self.spinMinimumX.setObjectName("spinMinimumX")
        self.horizontalLayout_4.addWidget(self.spinMinimumX)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtGui.QLabel(self.groupBox_5)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.spinMaximumX = QtGui.QDoubleSpinBox(self.groupBox_5)
        self.spinMaximumX.setMinimum(-1000.0)
        self.spinMaximumX.setMaximum(10000.0)
        self.spinMaximumX.setSingleStep(0.1)
        self.spinMaximumX.setProperty("value", 1.0)
        self.spinMaximumX.setObjectName("spinMaximumX")
        self.horizontalLayout_2.addWidget(self.spinMaximumX)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_6.addWidget(self.groupBox_5)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lblTitle = QtGui.QLabel(ExtendedErrorBarDialog)
        self.lblTitle.setObjectName("lblTitle")
        self.horizontalLayout_9.addWidget(self.lblTitle)
        self.txtXLabel = QtGui.QLineEdit(ExtendedErrorBarDialog)
        self.txtXLabel.setObjectName("txtXLabel")
        self.horizontalLayout_9.addWidget(self.txtXLabel)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.buttonBox = QtGui.QDialogButtonBox(ExtendedErrorBarDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_3.addWidget(self.buttonBox)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)

        self.retranslateUi(ExtendedErrorBarDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), ExtendedErrorBarDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), ExtendedErrorBarDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ExtendedErrorBarDialog)

    def retranslateUi(self, ExtendedErrorBarDialog):
        ExtendedErrorBarDialog.setWindowTitle(QtGui.QApplication.translate("ExtendedErrorBarDialog", "Configure plot", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("ExtendedErrorBarDialog", "Sorting", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ExtendedErrorBarDialog", "Field:", None, QtGui.QApplication.UnicodeUTF8))
        self.cboSortingField.setItemText(0, QtGui.QApplication.translate("ExtendedErrorBarDialog", "p-values", None, QtGui.QApplication.UnicodeUTF8))
        self.cboSortingField.setItemText(1, QtGui.QApplication.translate("ExtendedErrorBarDialog", "Effect sizes", None, QtGui.QApplication.UnicodeUTF8))
        self.cboSortingField.setItemText(2, QtGui.QApplication.translate("ExtendedErrorBarDialog", "Feature labels", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("ExtendedErrorBarDialog", "Multiple comparisons", None, QtGui.QApplication.UnicodeUTF8))
        self.chkCorrectedPvalues.setText(QtGui.QApplication.translate("ExtendedErrorBarDialog", "Show corrected p-values", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("ExtendedErrorBarDialog", "Figure size", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFigureWidth.setText(QtGui.QApplication.translate("ExtendedErrorBarDialog", "Width:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFigureHeight.setText(QtGui.QApplication.translate("ExtendedErrorBarDialog", "Row height:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("ExtendedErrorBarDialog", "Figure elements", None, QtGui.QApplication.UnicodeUTF8))
        self.chkShowSeq.setText(QtGui.QApplication.translate("ExtendedErrorBarDialog", "Sequences subplot", None, QtGui.QApplication.UnicodeUTF8))
        self.chkPValueLabels.setText(QtGui.QApplication.translate("ExtendedErrorBarDialog", "p-value labels", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("ExtendedErrorBarDialog", "Error bar x-axis limits", None, QtGui.QApplication.UnicodeUTF8))
        self.chkCustomLimits.setText(QtGui.QApplication.translate("ExtendedErrorBarDialog", "Use custom limits", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ExtendedErrorBarDialog", "Minimum:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ExtendedErrorBarDialog", "Maximum:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTitle.setText(QtGui.QApplication.translate("ExtendedErrorBarDialog", "Quantity plot x-axis title:", None, QtGui.QApplication.UnicodeUTF8))

