execution:
    uuid: 424e20e3-5223-40b0-9a57-10b4d69310d3
    runtime:
        start: 2018-10-20T03:20:24.862351+07:00
        end: 2018-10-20T03:20:29.304801+07:00
        duration: 4 seconds, and 442450 microseconds

action:
    type: method
    plugin: !ref 'environment:plugins:vsearch'
    action: uchime_denovo
    inputs:
    -   sequences: 738372b3-f4aa-4862-afeb-9702f5493779
    -   table: 4ae5c1d5-b313-47b3-9b30-fa686f114e6e
    parameters:
    -   dn: 1.4
    -   mindiffs: 3
    -   mindiv: 0.8
    -   minh: 0.28
    -   xn: 8.0
    output-name: nonchimeras

environment:
    platform: macosx-10.9-x86_64
    python: |-
        3.5.4 | packaged by conda-forge | (default, Aug 10 2017, 01:41:15)
        [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
    framework: 2017.12.0
    plugins:
        vsearch:
            version: 2017.12.0
            website: https://github.com/qiime2/q2-vsearch
    python-packages:
        widgetsnbextension: 3.1.0
        wheel: 0.30.0
        webencodings: '0.5'
        wcwidth: 0.1.7
        urllib3: '1.22'
        unifrac: 0.9.2
        traitlets: 4.3.2
        tornado: 4.5.2
        testpath: 0.3.1
        terminado: 0.8.1
        statsmodels: 0.8.0
        six: 1.11.0
        simplegeneric: 0.8.1
        setuptools: 38.2.4
        seaborn: 0.8.1
        scipy: 0.19.1
        scikit-learn: 0.19.1
        scikit-bio: 0.5.1
        requests: 2.18.4
        qiime2: 2017.12.0
        q2templates: 2017.12.0
        q2cli: 2017.12.0
        q2-vsearch: 2017.12.0
        q2-types: 2017.12.0
        q2-taxa: 2017.12.0
        q2-sample-classifier: 2017.12.0
        q2-quality-filter: 2017.12.0
        q2-quality-control: 2017.12.0
        q2-phylogeny: 2017.12.0
        q2-metadata: 2017.12.0
        q2-longitudinal: 2017.12.0
        q2-gneiss: 2017.12.0
        q2-feature-table: 2017.12.0
        q2-feature-classifier: 2017.12.0
        q2-emperor: 2017.12.0
        q2-diversity: 2017.12.0
        q2-demux: 2017.12.0
        q2-deblur: 2017.12.0
        q2-dada2: 2017.12.0
        q2-cutadapt: 2017.12.0
        q2-composition: 2017.12.0
        q2-alignment: 2017.12.0
        pyzmq: 16.0.2
        PyYAML: '3.12'
        pytz: '2017.3'
        python-dateutil: 2.6.1
        PySocks: 1.6.7
        pyparsing: 2.2.0
        pyOpenSSL: 17.4.0
        Pygments: 2.2.0
        pycparser: '2.18'
        ptyprocess: 0.5.2
        psutil: 5.4.0
        prompt-toolkit: 1.0.15
        pip: 9.0.1
        pickleshare: 0.7.4
        pexpect: 4.3.1
        patsy: 0.4.1
        pandocfilters: 1.4.1
        pandas: 0.22.0
        numpy: 1.12.1
        notebook: 5.2.2
        nose: 1.3.7
        nbformat: 4.4.0
        nbconvert: 5.3.1
        natsort: 5.0.2
        msgpack-python: 0.4.8
        mistune: 0.8.3
        matplotlib: 2.1.1
        MarkupSafe: '1.0'
        lockfile: 0.12.2
        jupyter-core: 4.4.0
        jupyter-client: 5.2.0
        jsonschema: 2.6.0
        Jinja2: '2.10'
        jedi: 0.10.2
        ipywidgets: 7.1.0
        ipython: 6.2.1
        ipython-genutils: 0.2.0
        ipykernel: 4.7.0
        idna: '2.6'
        html5lib: 1.0.1
        h5py: 2.7.0
        future: 0.16.0
        fastcluster: 1.1.24
        entrypoints: 0.2.3
        emperor: 1.0.0b13
        decorator: 4.1.2
        deblur: 1.0.3
        Cython: 0.27.3
        cutadapt: '1.15'
        cryptography: 2.1.4
        click: '6.7'
        chardet: 3.0.4
        cffi: 1.11.2
        certifi: 2017.11.5
        CacheControl: 0.12.3
        bokeh: 0.12.13
        bleach: 2.0.0
        backports.functools-lru-cache: '1.4'
        asn1crypto: 0.22.0
        appnope: 0.1.0
        biom-format: 2.1.6
        cycler: 0.10.0
        gneiss: 0.4.2
        ijson: '2.3'
        tzlocal: '1.3'
        xopen: 0.3.2
