# Creating rarefaction plot generated by mothur
# code to generate rarefaction (step 26) is here: https://github.com/jessicamizzi/mothur-commands/blob/master/workflow.md
rm(list=ls())
args <- commandArgs(TRUE)
library("reshape2")
library("ggplot2")

# load data
# replace this with your data file
rareDataMessy <- read.table(args[1], header = TRUE)


# Clean data file (no high or low confidence intervals)

# grep command may need to be changed. The idea is to pick out columns that are not hci or lci
rareDataColumnsPrimary <- rareDataMessy[grepl("X2", names(rareDataMessy))]
#tt=names(rareDataColumnsPrimary)

# this takes numsampled column from original data
numSampled <- rareDataMessy[ ,c("numsampled")]

# this combines numsampled column with grepped columns
rareData <- cbind(numSampled,rareDataColumnsPrimary)
names(rareData)<-gsub(x=names(rareData), pattern = "X2.", replacement = "")
## Plot data with ggplot2

# transform data to long form
longRareData <- melt(rareData, id.vars = "numSampled")
head(longRareData)

# plotting
options(scipen = 999) #turn it off, back on use options(scipen=0)
p=ggplot(data = longRareData, 
         aes(x = numSampled, y = value, color = variable)) +
  geom_line(na.rm=TRUE) + 
  ggtitle("") +
  scale_color_manual(values=rainbow(length(names(rareDataColumnsPrimary)))) +
  labs(x = "# Sequences sampled", y = "Observed OTUs") +
  guides(color = guide_legend("")) +
  theme_bw() + theme(legend.position="bottom",legend.text=element_text(size=12),text=element_text(size=14),axis.text.x=element_text(size=12),axis.text.y=element_text(size=12))#, panel.border = element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) #


#args[2] = "test_phylotype.svg"
svg(args[2],width=7,height=6)
#p
#p+scale_x_continuous(limits = c(0,max(rareDataMessy[,names(rareDataMessy) != "numsampled"])))

#args[3] = minimum
p+scale_x_continuous(limits = c(0,as.numeric(args[3])))
dev.off()


# args <- commandArgs(TRUE)
# data = read.table(args[1], header = T)

# #k = length(grep(x = colnames(data),pattern = "^X2"))
# # num <-grep(x = colnames(data),pattern = "^X2")
# # print(num[1])
# df <- read.table(args[1], header = TRUE)

# k <- sample(colnames(df))
# r <- grep("^X2", k, value = TRUE)
# te = 1
# name_sam = c()
# color_sam = c()
# for (i in r) {
#     name_sam <- c(name_sam, i)
# }

# #png(args[2], width = 8, height = 6, units = "in", res = 300)
# svg(args[2],width=8,height=6)

# cl <- rainbow(length(r))
# for (i in r) {
#     if (te == 1) {
#         print(i)
#         print(data[, i])
#         plot(x = data$numsampled, y = data[, i], type = "l", col = cl[te], xlab = "# sequences sampled", ylab = "Observed OTUs", ylim = c(0, max(data[,names(data) != "numsampled"],na.rm=TRUE)+50))#, xlim=c(0,130000), ylim=c(0,900))
#         color_sam <- c(color_sam, cl[te])
#     }else {
#         print(i)
#         print(data[, i])
#         lines(x = data$numsampled, y = data[, i], type = "l", col = cl[te])
#         color_sam <- c(color_sam, cl[te])
#     }
#     te = te + 1
# }

# legend('topleft', name_sam, pch = c(16, 16, 16, 16), lty = c(1, 1, 1, 1), col = c(color_sam, ncol = 1), cex = 0.8)
# dev.off()
