# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'profileBarPlot.ui'
#
# Created: Sat Jul 17 12:03:36 2010
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ProfileBarPlotDialog(object):
    def setupUi(self, ProfileBarPlotDialog):
        ProfileBarPlotDialog.setObjectName("ProfileBarPlotDialog")
        ProfileBarPlotDialog.resize(417, 255)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ProfileBarPlotDialog.sizePolicy().hasHeightForWidth())
        ProfileBarPlotDialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../icons/programIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ProfileBarPlotDialog.setWindowIcon(icon)
        self.verticalLayout_5 = QtGui.QVBoxLayout(ProfileBarPlotDialog)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblFieldToPlot = QtGui.QLabel(ProfileBarPlotDialog)
        self.lblFieldToPlot.setObjectName("lblFieldToPlot")
        self.horizontalLayout.addWidget(self.lblFieldToPlot)
        self.cboFieldToPlot = QtGui.QComboBox(ProfileBarPlotDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboFieldToPlot.sizePolicy().hasHeightForWidth())
        self.cboFieldToPlot.setSizePolicy(sizePolicy)
        self.cboFieldToPlot.setObjectName("cboFieldToPlot")
        self.cboFieldToPlot.addItem("")
        self.cboFieldToPlot.addItem("")
        self.horizontalLayout.addWidget(self.cboFieldToPlot)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.groupBox_2 = QtGui.QGroupBox(ProfileBarPlotDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lblSampleName1 = QtGui.QLabel(self.groupBox_2)
        self.lblSampleName1.setObjectName("lblSampleName1")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblSampleName1)
        self.txtSampleName1 = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtSampleName1.sizePolicy().hasHeightForWidth())
        self.txtSampleName1.setSizePolicy(sizePolicy)
        self.txtSampleName1.setObjectName("txtSampleName1")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.txtSampleName1)
        self.lblSampleName2 = QtGui.QLabel(self.groupBox_2)
        self.lblSampleName2.setObjectName("lblSampleName2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblSampleName2)
        self.txtSampleName2 = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtSampleName2.sizePolicy().hasHeightForWidth())
        self.txtSampleName2.setSizePolicy(sizePolicy)
        self.txtSampleName2.setObjectName("txtSampleName2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.txtSampleName2)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_3 = QtGui.QGroupBox(ProfileBarPlotDialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.spinFigColWidth = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.spinFigColWidth.setDecimals(2)
        self.spinFigColWidth.setMinimum(0.01)
        self.spinFigColWidth.setMaximum(10.0)
        self.spinFigColWidth.setSingleStep(0.01)
        self.spinFigColWidth.setProperty("value", 0.5)
        self.spinFigColWidth.setObjectName("spinFigColWidth")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinFigColWidth)
        self.lblFigureHeight = QtGui.QLabel(self.groupBox_3)
        self.lblFigureHeight.setObjectName("lblFigureHeight")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblFigureHeight)
        self.spinFigHeight = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.spinFigHeight.setMinimum(0.1)
        self.spinFigHeight.setMaximum(20.0)
        self.spinFigHeight.setSingleStep(0.05)
        self.spinFigHeight.setProperty("value", 6.0)
        self.spinFigHeight.setObjectName("spinFigHeight")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinFigHeight)
        self.lblFigureWidth = QtGui.QLabel(self.groupBox_3)
        self.lblFigureWidth.setObjectName("lblFigureWidth")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblFigureWidth)
        self.verticalLayout_6.addLayout(self.formLayout_2)
        self.horizontalLayout_4.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(ProfileBarPlotDialog)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.chkShowCIs = QtGui.QCheckBox(self.groupBox_4)
        self.chkShowCIs.setChecked(True)
        self.chkShowCIs.setObjectName("chkShowCIs")
        self.verticalLayout_3.addWidget(self.chkShowCIs)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(self.groupBox_4)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.spinEndCapSize = QtGui.QSpinBox(self.groupBox_4)
        self.spinEndCapSize.setMaximum(100)
        self.spinEndCapSize.setObjectName("spinEndCapSize")
        self.horizontalLayout_2.addWidget(self.spinEndCapSize)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addWidget(self.groupBox_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.groupBox = QtGui.QGroupBox(ProfileBarPlotDialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioLegendPosBest = QtGui.QRadioButton(self.groupBox)
        self.radioLegendPosBest.setChecked(True)
        self.radioLegendPosBest.setObjectName("radioLegendPosBest")
        self.verticalLayout.addWidget(self.radioLegendPosBest)
        self.radioLegendPosUpperRight = QtGui.QRadioButton(self.groupBox)
        self.radioLegendPosUpperRight.setObjectName("radioLegendPosUpperRight")
        self.verticalLayout.addWidget(self.radioLegendPosUpperRight)
        self.radioLegendPosCentreRight = QtGui.QRadioButton(self.groupBox)
        self.radioLegendPosCentreRight.setObjectName("radioLegendPosCentreRight")
        self.verticalLayout.addWidget(self.radioLegendPosCentreRight)
        self.radioLegendPosLowerRight = QtGui.QRadioButton(self.groupBox)
        self.radioLegendPosLowerRight.setObjectName("radioLegendPosLowerRight")
        self.verticalLayout.addWidget(self.radioLegendPosLowerRight)
        self.radioLegendPosUpperLeft = QtGui.QRadioButton(self.groupBox)
        self.radioLegendPosUpperLeft.setObjectName("radioLegendPosUpperLeft")
        self.verticalLayout.addWidget(self.radioLegendPosUpperLeft)
        self.radioLegendPosCentreLeft = QtGui.QRadioButton(self.groupBox)
        self.radioLegendPosCentreLeft.setObjectName("radioLegendPosCentreLeft")
        self.verticalLayout.addWidget(self.radioLegendPosCentreLeft)
        self.radioLegendPosLowerLeft = QtGui.QRadioButton(self.groupBox)
        self.radioLegendPosLowerLeft.setChecked(False)
        self.radioLegendPosLowerLeft.setObjectName("radioLegendPosLowerLeft")
        self.verticalLayout.addWidget(self.radioLegendPosLowerLeft)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.buttonBox = QtGui.QDialogButtonBox(ProfileBarPlotDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_5.addWidget(self.buttonBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)

        self.retranslateUi(ProfileBarPlotDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), ProfileBarPlotDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), ProfileBarPlotDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ProfileBarPlotDialog)

    def retranslateUi(self, ProfileBarPlotDialog):
        ProfileBarPlotDialog.setWindowTitle(QtGui.QApplication.translate("ProfileBarPlotDialog", "Profile bar plot", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFieldToPlot.setText(QtGui.QApplication.translate("ProfileBarPlotDialog", "Field to plot:", None, QtGui.QApplication.UnicodeUTF8))
        self.cboFieldToPlot.setItemText(0, QtGui.QApplication.translate("ProfileBarPlotDialog", "Number of sequences", None, QtGui.QApplication.UnicodeUTF8))
        self.cboFieldToPlot.setItemText(1, QtGui.QApplication.translate("ProfileBarPlotDialog", "Proportion of sequences", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("ProfileBarPlotDialog", "Sample names", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSampleName1.setText(QtGui.QApplication.translate("ProfileBarPlotDialog", "Sample name 1:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSampleName2.setText(QtGui.QApplication.translate("ProfileBarPlotDialog", "Sample name 2:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("ProfileBarPlotDialog", "Figure size", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFigureHeight.setText(QtGui.QApplication.translate("ProfileBarPlotDialog", "Height:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFigureWidth.setText(QtGui.QApplication.translate("ProfileBarPlotDialog", "Column width:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("ProfileBarPlotDialog", "Confidence Intervals", None, QtGui.QApplication.UnicodeUTF8))
        self.chkShowCIs.setText(QtGui.QApplication.translate("ProfileBarPlotDialog", "Show CIs", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ProfileBarPlotDialog", "End cap size:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("ProfileBarPlotDialog", "Legend position", None, QtGui.QApplication.UnicodeUTF8))
        self.radioLegendPosBest.setText(QtGui.QApplication.translate("ProfileBarPlotDialog", "Best", None, QtGui.QApplication.UnicodeUTF8))
        self.radioLegendPosUpperRight.setText(QtGui.QApplication.translate("ProfileBarPlotDialog", "Upper right", None, QtGui.QApplication.UnicodeUTF8))
        self.radioLegendPosCentreRight.setText(QtGui.QApplication.translate("ProfileBarPlotDialog", "Centre right", None, QtGui.QApplication.UnicodeUTF8))
        self.radioLegendPosLowerRight.setText(QtGui.QApplication.translate("ProfileBarPlotDialog", "Lower right", None, QtGui.QApplication.UnicodeUTF8))
        self.radioLegendPosUpperLeft.setText(QtGui.QApplication.translate("ProfileBarPlotDialog", "Upper left", None, QtGui.QApplication.UnicodeUTF8))
        self.radioLegendPosCentreLeft.setText(QtGui.QApplication.translate("ProfileBarPlotDialog", "Centre left", None, QtGui.QApplication.UnicodeUTF8))
        self.radioLegendPosLowerLeft.setText(QtGui.QApplication.translate("ProfileBarPlotDialog", "Lower left", None, QtGui.QApplication.UnicodeUTF8))

