# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'profileScatterPlot.ui'
#
# Created: Sat Jul 17 12:11:51 2010
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ProfileScatterPlotDialog(object):
    def setupUi(self, ProfileScatterPlotDialog):
        ProfileScatterPlotDialog.setObjectName("ProfileScatterPlotDialog")
        ProfileScatterPlotDialog.resize(403, 242)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ProfileScatterPlotDialog.sizePolicy().hasHeightForWidth())
        ProfileScatterPlotDialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../icons/programIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ProfileScatterPlotDialog.setWindowIcon(icon)
        self.verticalLayout_5 = QtGui.QVBoxLayout(ProfileScatterPlotDialog)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_2 = QtGui.QGroupBox(ProfileScatterPlotDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.lblSampleName1 = QtGui.QLabel(self.groupBox_2)
        self.lblSampleName1.setObjectName("lblSampleName1")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblSampleName1)
        self.txtSampleName1 = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtSampleName1.sizePolicy().hasHeightForWidth())
        self.txtSampleName1.setSizePolicy(sizePolicy)
        self.txtSampleName1.setObjectName("txtSampleName1")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.txtSampleName1)
        self.lblSampleName2 = QtGui.QLabel(self.groupBox_2)
        self.lblSampleName2.setObjectName("lblSampleName2")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblSampleName2)
        self.txtSampleName2 = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtSampleName2.sizePolicy().hasHeightForWidth())
        self.txtSampleName2.setSizePolicy(sizePolicy)
        self.txtSampleName2.setObjectName("txtSampleName2")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.txtSampleName2)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_3 = QtGui.QGroupBox(ProfileScatterPlotDialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lblFigureWidth = QtGui.QLabel(self.groupBox_3)
        self.lblFigureWidth.setObjectName("lblFigureWidth")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblFigureWidth)
        self.spinFigWidth = QtGui.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinFigWidth.sizePolicy().hasHeightForWidth())
        self.spinFigWidth.setSizePolicy(sizePolicy)
        self.spinFigWidth.setDecimals(2)
        self.spinFigWidth.setMinimum(0.5)
        self.spinFigWidth.setMaximum(20.0)
        self.spinFigWidth.setSingleStep(0.5)
        self.spinFigWidth.setProperty("value", 6.0)
        self.spinFigWidth.setObjectName("spinFigWidth")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinFigWidth)
        self.lblFigureHeight = QtGui.QLabel(self.groupBox_3)
        self.lblFigureHeight.setObjectName("lblFigureHeight")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblFigureHeight)
        self.spinFigHeight = QtGui.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinFigHeight.sizePolicy().hasHeightForWidth())
        self.spinFigHeight.setSizePolicy(sizePolicy)
        self.spinFigHeight.setMinimum(0.5)
        self.spinFigHeight.setMaximum(20.0)
        self.spinFigHeight.setSingleStep(0.05)
        self.spinFigHeight.setProperty("value", 6.0)
        self.spinFigHeight.setObjectName("spinFigHeight")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinFigHeight)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(ProfileScatterPlotDialog)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.chkShowCIs = QtGui.QCheckBox(self.groupBox_4)
        self.chkShowCIs.setChecked(True)
        self.chkShowCIs.setObjectName("chkShowCIs")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.chkShowCIs)
        self.label = QtGui.QLabel(self.groupBox_4)
        self.label.setObjectName("label")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.spinEndCapSize = QtGui.QSpinBox(self.groupBox_4)
        self.spinEndCapSize.setEnabled(False)
        self.spinEndCapSize.setMaximum(100)
        self.spinEndCapSize.setObjectName("spinEndCapSize")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinEndCapSize)
        self.verticalLayout_3.addLayout(self.formLayout_4)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.groupBox = QtGui.QGroupBox(ProfileScatterPlotDialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.chkShowHistogram = QtGui.QCheckBox(self.groupBox)
        self.chkShowHistogram.setObjectName("chkShowHistogram")
        self.verticalLayout_4.addWidget(self.chkShowHistogram)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.spinNumBins = QtGui.QSpinBox(self.groupBox)
        self.spinNumBins.setMaximum(1000)
        self.spinNumBins.setObjectName("spinNumBins")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinNumBins)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.spinHistogramSize = QtGui.QDoubleSpinBox(self.groupBox)
        self.spinHistogramSize.setMaximum(6.0)
        self.spinHistogramSize.setSingleStep(0.25)
        self.spinHistogramSize.setObjectName("spinHistogramSize")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinHistogramSize)
        self.verticalLayout_4.addLayout(self.formLayout_3)
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.buttonBox = QtGui.QDialogButtonBox(ProfileScatterPlotDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_3.addWidget(self.buttonBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)

        self.retranslateUi(ProfileScatterPlotDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), ProfileScatterPlotDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), ProfileScatterPlotDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ProfileScatterPlotDialog)

    def retranslateUi(self, ProfileScatterPlotDialog):
        ProfileScatterPlotDialog.setWindowTitle(QtGui.QApplication.translate("ProfileScatterPlotDialog", "Profile scatter plot", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("ProfileScatterPlotDialog", "Sample names", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSampleName1.setText(QtGui.QApplication.translate("ProfileScatterPlotDialog", "Sample name 1:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSampleName2.setText(QtGui.QApplication.translate("ProfileScatterPlotDialog", "Sample name 2:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("ProfileScatterPlotDialog", "Figure size", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFigureWidth.setText(QtGui.QApplication.translate("ProfileScatterPlotDialog", "Width:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFigureHeight.setText(QtGui.QApplication.translate("ProfileScatterPlotDialog", "Height:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("ProfileScatterPlotDialog", "Confidence Intervals", None, QtGui.QApplication.UnicodeUTF8))
        self.chkShowCIs.setText(QtGui.QApplication.translate("ProfileScatterPlotDialog", "Show CIs", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ProfileScatterPlotDialog", "End cap size:", None, QtGui.QApplication.UnicodeUTF8))
        self.spinEndCapSize.setToolTip(QtGui.QApplication.translate("ProfileScatterPlotDialog", "Currently not implemented", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("ProfileScatterPlotDialog", "Histogram", None, QtGui.QApplication.UnicodeUTF8))
        self.chkShowHistogram.setText(QtGui.QApplication.translate("ProfileScatterPlotDialog", "Show histograms", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ProfileScatterPlotDialog", "Bins:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ProfileScatterPlotDialog", "Size:", None, QtGui.QApplication.UnicodeUTF8))

