# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Mon Sep 06 16:00:17 2010
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1103, 700)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/programIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setFrameShape(QtGui.QFrame.NoFrame)
        self.splitter.setFrameShadow(QtGui.QFrame.Plain)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(5)
        self.splitter.setObjectName("splitter")
        self.scrollArea = QtGui.QScrollArea(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaSideBar = QtGui.QWidget(self.scrollArea)
        self.scrollAreaSideBar.setGeometry(QtCore.QRect(0, 0, 371, 1256))
        self.scrollAreaSideBar.setObjectName("scrollAreaSideBar")
        self.verticalLayout = QtGui.QVBoxLayout(self.scrollAreaSideBar)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setMargin(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupProfile = QtGui.QGroupBox(self.scrollAreaSideBar)
        self.groupProfile.setFlat(False)
        self.groupProfile.setObjectName("groupProfile")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupProfile)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setMargin(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.btnProfileArrow = QtGui.QPushButton(self.groupProfile)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/downArrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnProfileArrow.setIcon(icon1)
        self.btnProfileArrow.setObjectName("btnProfileArrow")
        self.horizontalLayout_20.addWidget(self.btnProfileArrow)
        self.btnProfileTab = QtGui.QPushButton(self.groupProfile)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnProfileTab.sizePolicy().hasHeightForWidth())
        self.btnProfileTab.setSizePolicy(sizePolicy)
        self.btnProfileTab.setMinimumSize(QtCore.QSize(0, 0))
        self.btnProfileTab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnProfileTab.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.btnProfileTab.setFont(font)
        self.btnProfileTab.setFlat(False)
        self.btnProfileTab.setObjectName("btnProfileTab")
        self.horizontalLayout_20.addWidget(self.btnProfileTab)
        self.verticalLayout_4.addLayout(self.horizontalLayout_20)
        self.widgetProfile = QtGui.QWidget(self.groupProfile)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widgetProfile.sizePolicy().hasHeightForWidth())
        self.widgetProfile.setSizePolicy(sizePolicy)
        self.widgetProfile.setObjectName("widgetProfile")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.widgetProfile)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_14 = QtGui.QLabel(self.widgetProfile)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_14)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.cboSample1 = QtGui.QComboBox(self.widgetProfile)
        self.cboSample1.setObjectName("cboSample1")
        self.horizontalLayout_7.addWidget(self.cboSample1)
        self.btnSample1Colour = QtGui.QPushButton(self.widgetProfile)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSample1Colour.sizePolicy().hasHeightForWidth())
        self.btnSample1Colour.setSizePolicy(sizePolicy)
        self.btnSample1Colour.setMinimumSize(QtCore.QSize(22, 22))
        self.btnSample1Colour.setMaximumSize(QtCore.QSize(22, 22))
        self.btnSample1Colour.setObjectName("btnSample1Colour")
        self.horizontalLayout_7.addWidget(self.btnSample1Colour)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.label_15 = QtGui.QLabel(self.widgetProfile)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_15)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.cboSample2 = QtGui.QComboBox(self.widgetProfile)
        self.cboSample2.setObjectName("cboSample2")
        self.horizontalLayout_12.addWidget(self.cboSample2)
        self.btnSample2Colour = QtGui.QPushButton(self.widgetProfile)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSample2Colour.sizePolicy().hasHeightForWidth())
        self.btnSample2Colour.setSizePolicy(sizePolicy)
        self.btnSample2Colour.setMinimumSize(QtCore.QSize(22, 22))
        self.btnSample2Colour.setMaximumSize(QtCore.QSize(22, 22))
        self.btnSample2Colour.setObjectName("btnSample2Colour")
        self.horizontalLayout_12.addWidget(self.btnSample2Colour)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_12)
        self.verticalLayout_5.addLayout(self.formLayout)
        self.line_6 = QtGui.QFrame(self.widgetProfile)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_5.addWidget(self.line_6)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_11 = QtGui.QLabel(self.widgetProfile)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_11)
        self.cboParentalLevel = QtGui.QComboBox(self.widgetProfile)
        self.cboParentalLevel.setObjectName("cboParentalLevel")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.cboParentalLevel)
        self.lblProfile = QtGui.QLabel(self.widgetProfile)
        self.lblProfile.setObjectName("lblProfile")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblProfile)
        self.cboProfileLevel = QtGui.QComboBox(self.widgetProfile)
        self.cboProfileLevel.setObjectName("cboProfileLevel")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.cboProfileLevel)
        self.verticalLayout_5.addLayout(self.formLayout_3)
        self.line_5 = QtGui.QFrame(self.widgetProfile)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_5.addWidget(self.line_5)
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName("formLayout_5")
        self.lblParentCategories = QtGui.QLabel(self.widgetProfile)
        self.lblParentCategories.setObjectName("lblParentCategories")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblParentCategories)
        self.txtNumParentCategories = QtGui.QLineEdit(self.widgetProfile)
        self.txtNumParentCategories.setReadOnly(True)
        self.txtNumParentCategories.setObjectName("txtNumParentCategories")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.txtNumParentCategories)
        self.lblFeatures = QtGui.QLabel(self.widgetProfile)
        self.lblFeatures.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblFeatures.setObjectName("lblFeatures")
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblFeatures)
        self.txtNumFeatures = QtGui.QLineEdit(self.widgetProfile)
        self.txtNumFeatures.setReadOnly(True)
        self.txtNumFeatures.setObjectName("txtNumFeatures")
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.txtNumFeatures)
        self.lblTotalSeqs = QtGui.QLabel(self.widgetProfile)
        self.lblTotalSeqs.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblTotalSeqs.setObjectName("lblTotalSeqs")
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblTotalSeqs)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.txtTotalSeqs1 = QtGui.QLineEdit(self.widgetProfile)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtTotalSeqs1.sizePolicy().hasHeightForWidth())
        self.txtTotalSeqs1.setSizePolicy(sizePolicy)
        self.txtTotalSeqs1.setMinimumSize(QtCore.QSize(0, 0))
        self.txtTotalSeqs1.setMaximumSize(QtCore.QSize(100, 16777215))
        self.txtTotalSeqs1.setBaseSize(QtCore.QSize(25, 0))
        self.txtTotalSeqs1.setReadOnly(True)
        self.txtTotalSeqs1.setObjectName("txtTotalSeqs1")
        self.horizontalLayout_4.addWidget(self.txtTotalSeqs1)
        spacerItem = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.txtTotalSeqs2 = QtGui.QLineEdit(self.widgetProfile)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtTotalSeqs2.sizePolicy().hasHeightForWidth())
        self.txtTotalSeqs2.setSizePolicy(sizePolicy)
        self.txtTotalSeqs2.setMinimumSize(QtCore.QSize(0, 0))
        self.txtTotalSeqs2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.txtTotalSeqs2.setBaseSize(QtCore.QSize(25, 0))
        self.txtTotalSeqs2.setReadOnly(True)
        self.txtTotalSeqs2.setObjectName("txtTotalSeqs2")
        self.horizontalLayout_4.addWidget(self.txtTotalSeqs2)
        self.formLayout_5.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.verticalLayout_5.addLayout(self.formLayout_5)
        self.verticalLayout_4.addWidget(self.widgetProfile)
        self.verticalLayout.addWidget(self.groupProfile)
        self.groupStatProperties = QtGui.QGroupBox(self.scrollAreaSideBar)
        self.groupStatProperties.setFlat(False)
        self.groupStatProperties.setObjectName("groupStatProperties")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupStatProperties)
        self.verticalLayout_6.setSpacing(2)
        self.verticalLayout_6.setMargin(2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.btnStatisticsArrow = QtGui.QPushButton(self.groupStatProperties)
        self.btnStatisticsArrow.setIcon(icon1)
        self.btnStatisticsArrow.setObjectName("btnStatisticsArrow")
        self.horizontalLayout_21.addWidget(self.btnStatisticsArrow)
        self.btnStatisticsTab = QtGui.QPushButton(self.groupStatProperties)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStatisticsTab.sizePolicy().hasHeightForWidth())
        self.btnStatisticsTab.setSizePolicy(sizePolicy)
        self.btnStatisticsTab.setMinimumSize(QtCore.QSize(0, 0))
        self.btnStatisticsTab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnStatisticsTab.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.btnStatisticsTab.setFont(font)
        self.btnStatisticsTab.setCheckable(False)
        self.btnStatisticsTab.setChecked(False)
        self.btnStatisticsTab.setObjectName("btnStatisticsTab")
        self.horizontalLayout_21.addWidget(self.btnStatisticsTab)
        self.verticalLayout_6.addLayout(self.horizontalLayout_21)
        self.widgetStatisticalProp = QtGui.QWidget(self.groupStatProperties)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widgetStatisticalProp.sizePolicy().hasHeightForWidth())
        self.widgetStatisticalProp.setSizePolicy(sizePolicy)
        self.widgetStatisticalProp.setObjectName("widgetStatisticalProp")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.widgetStatisticalProp)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lblStatisticalTest = QtGui.QLabel(self.widgetStatisticalProp)
        self.lblStatisticalTest.setObjectName("lblStatisticalTest")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblStatisticalTest)
        self.cboStatTests = QtGui.QComboBox(self.widgetStatisticalProp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboStatTests.sizePolicy().hasHeightForWidth())
        self.cboStatTests.setSizePolicy(sizePolicy)
        self.cboStatTests.setMinimumSize(QtCore.QSize(0, 20))
        self.cboStatTests.setObjectName("cboStatTests")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.cboStatTests)
        self.label_7 = QtGui.QLabel(self.widgetStatisticalProp)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_7)
        self.cboSignTestType = QtGui.QComboBox(self.widgetStatisticalProp)
        self.cboSignTestType.setObjectName("cboSignTestType")
        self.cboSignTestType.addItem("")
        self.cboSignTestType.addItem("")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.cboSignTestType)
        self.lblConfidenceIntervalMethod = QtGui.QLabel(self.widgetStatisticalProp)
        self.lblConfidenceIntervalMethod.setObjectName("lblConfidenceIntervalMethod")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblConfidenceIntervalMethod)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.cboConfIntervMethods = QtGui.QComboBox(self.widgetStatisticalProp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboConfIntervMethods.sizePolicy().hasHeightForWidth())
        self.cboConfIntervMethods.setSizePolicy(sizePolicy)
        self.cboConfIntervMethods.setObjectName("cboConfIntervMethods")
        self.horizontalLayout_19.addWidget(self.cboConfIntervMethods)
        self.cboNominalCoverage = QtGui.QComboBox(self.widgetStatisticalProp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboNominalCoverage.sizePolicy().hasHeightForWidth())
        self.cboNominalCoverage.setSizePolicy(sizePolicy)
        self.cboNominalCoverage.setMinimumSize(QtCore.QSize(0, 20))
        self.cboNominalCoverage.setEditable(True)
        self.cboNominalCoverage.setObjectName("cboNominalCoverage")
        self.cboNominalCoverage.addItem("")
        self.cboNominalCoverage.addItem("")
        self.cboNominalCoverage.addItem("")
        self.cboNominalCoverage.addItem("")
        self.cboNominalCoverage.addItem("")
        self.horizontalLayout_19.addWidget(self.cboNominalCoverage)
        self.formLayout_2.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_19)
        self.verticalLayout_11.addLayout(self.formLayout_2)
        self.line_2 = QtGui.QFrame(self.widgetStatisticalProp)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_11.addWidget(self.line_2)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_18 = QtGui.QLabel(self.widgetStatisticalProp)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_18.addWidget(self.label_18)
        self.cboMultCompMethod = QtGui.QComboBox(self.widgetStatisticalProp)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboMultCompMethod.sizePolicy().hasHeightForWidth())
        self.cboMultCompMethod.setSizePolicy(sizePolicy)
        self.cboMultCompMethod.setObjectName("cboMultCompMethod")
        self.horizontalLayout_18.addWidget(self.cboMultCompMethod)
        self.btnMultCompCorrectionInfo = QtGui.QPushButton(self.widgetStatisticalProp)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/Info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMultCompCorrectionInfo.setIcon(icon2)
        self.btnMultCompCorrectionInfo.setObjectName("btnMultCompCorrectionInfo")
        self.horizontalLayout_18.addWidget(self.btnMultCompCorrectionInfo)
        self.verticalLayout_11.addLayout(self.horizontalLayout_18)
        self.line_3 = QtGui.QFrame(self.widgetStatisticalProp)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_11.addWidget(self.line_3)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.btnRunTest = QtGui.QPushButton(self.widgetStatisticalProp)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRunTest.setIcon(icon3)
        self.btnRunTest.setCheckable(False)
        self.btnRunTest.setChecked(False)
        self.btnRunTest.setObjectName("btnRunTest")
        self.horizontalLayout_23.addWidget(self.btnRunTest)
        self.verticalLayout_11.addLayout(self.horizontalLayout_23)
        self.verticalLayout_6.addWidget(self.widgetStatisticalProp)
        self.verticalLayout.addWidget(self.groupStatProperties)
        self.groupFiltering = QtGui.QGroupBox(self.scrollAreaSideBar)
        self.groupFiltering.setFlat(False)
        self.groupFiltering.setObjectName("groupFiltering")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupFiltering)
        self.verticalLayout_12.setSpacing(2)
        self.verticalLayout_12.setMargin(2)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setSpacing(0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.btnFilteringArrow = QtGui.QPushButton(self.groupFiltering)
        self.btnFilteringArrow.setIcon(icon1)
        self.btnFilteringArrow.setObjectName("btnFilteringArrow")
        self.horizontalLayout_22.addWidget(self.btnFilteringArrow)
        self.btnFilteringTab = QtGui.QPushButton(self.groupFiltering)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFilteringTab.sizePolicy().hasHeightForWidth())
        self.btnFilteringTab.setSizePolicy(sizePolicy)
        self.btnFilteringTab.setMinimumSize(QtCore.QSize(0, 0))
        self.btnFilteringTab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnFilteringTab.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.btnFilteringTab.setFont(font)
        self.btnFilteringTab.setObjectName("btnFilteringTab")
        self.horizontalLayout_22.addWidget(self.btnFilteringTab)
        self.verticalLayout_12.addLayout(self.horizontalLayout_22)
        self.widgetFilter = QtGui.QWidget(self.groupFiltering)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widgetFilter.sizePolicy().hasHeightForWidth())
        self.widgetFilter.setSizePolicy(sizePolicy)
        self.widgetFilter.setObjectName("widgetFilter")
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.widgetFilter)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.chkSelectFeatures = QtGui.QCheckBox(self.widgetFilter)
        self.chkSelectFeatures.setObjectName("chkSelectFeatures")
        self.horizontalLayout_2.addWidget(self.chkSelectFeatures)
        self.btnSelectFeatures = QtGui.QPushButton(self.widgetFilter)
        self.btnSelectFeatures.setObjectName("btnSelectFeatures")
        self.horizontalLayout_2.addWidget(self.btnSelectFeatures)
        self.verticalLayout_13.addLayout(self.horizontalLayout_2)
        self.line = QtGui.QFrame(self.widgetFilter)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_13.addWidget(self.line)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.gridLayout.setObjectName("gridLayout")
        self.lblSignLevelFilter = QtGui.QLabel(self.widgetFilter)
        self.lblSignLevelFilter.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblSignLevelFilter.setObjectName("lblSignLevelFilter")
        self.gridLayout.addWidget(self.lblSignLevelFilter, 0, 0, 1, 1)
        self.spinSignLevelFilter = QtGui.QDoubleSpinBox(self.widgetFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinSignLevelFilter.sizePolicy().hasHeightForWidth())
        self.spinSignLevelFilter.setSizePolicy(sizePolicy)
        self.spinSignLevelFilter.setMinimumSize(QtCore.QSize(0, 0))
        self.spinSignLevelFilter.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.spinSignLevelFilter.setDecimals(5)
        self.spinSignLevelFilter.setMaximum(1.0)
        self.spinSignLevelFilter.setSingleStep(0.001)
        self.spinSignLevelFilter.setProperty("value", 0.05)
        self.spinSignLevelFilter.setObjectName("spinSignLevelFilter")
        self.gridLayout.addWidget(self.spinSignLevelFilter, 0, 1, 1, 1)
        self.chkEnableSignLevelFilter = QtGui.QCheckBox(self.widgetFilter)
        self.chkEnableSignLevelFilter.setChecked(True)
        self.chkEnableSignLevelFilter.setObjectName("chkEnableSignLevelFilter")
        self.gridLayout.addWidget(self.chkEnableSignLevelFilter, 0, 2, 1, 1)
        self.lblSeqFilter = QtGui.QLabel(self.widgetFilter)
        self.lblSeqFilter.setObjectName("lblSeqFilter")
        self.gridLayout.addWidget(self.lblSeqFilter, 2, 0, 1, 1)
        self.cboSeqFilter = QtGui.QComboBox(self.widgetFilter)
        self.cboSeqFilter.setEnabled(False)
        self.cboSeqFilter.setObjectName("cboSeqFilter")
        self.cboSeqFilter.addItem("")
        self.cboSeqFilter.addItem("")
        self.cboSeqFilter.addItem("")
        self.gridLayout.addWidget(self.cboSeqFilter, 2, 1, 1, 1)
        self.chkEnableSeqFilter = QtGui.QCheckBox(self.widgetFilter)
        self.chkEnableSeqFilter.setChecked(False)
        self.chkEnableSeqFilter.setObjectName("chkEnableSeqFilter")
        self.gridLayout.addWidget(self.chkEnableSeqFilter, 2, 2, 1, 1)
        self.lblSeqFilterSample1 = QtGui.QLabel(self.widgetFilter)
        self.lblSeqFilterSample1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSeqFilterSample1.setObjectName("lblSeqFilterSample1")
        self.gridLayout.addWidget(self.lblSeqFilterSample1, 3, 0, 1, 1)
        self.spinFilterSample1 = QtGui.QSpinBox(self.widgetFilter)
        self.spinFilterSample1.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinFilterSample1.sizePolicy().hasHeightForWidth())
        self.spinFilterSample1.setSizePolicy(sizePolicy)
        self.spinFilterSample1.setMinimumSize(QtCore.QSize(0, 0))
        self.spinFilterSample1.setMaximum(1000)
        self.spinFilterSample1.setProperty("value", 5)
        self.spinFilterSample1.setObjectName("spinFilterSample1")
        self.gridLayout.addWidget(self.spinFilterSample1, 3, 1, 1, 1)
        self.lblSeqFilterSample2 = QtGui.QLabel(self.widgetFilter)
        self.lblSeqFilterSample2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSeqFilterSample2.setObjectName("lblSeqFilterSample2")
        self.gridLayout.addWidget(self.lblSeqFilterSample2, 4, 0, 1, 1)
        self.spinFilterSample2 = QtGui.QSpinBox(self.widgetFilter)
        self.spinFilterSample2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinFilterSample2.sizePolicy().hasHeightForWidth())
        self.spinFilterSample2.setSizePolicy(sizePolicy)
        self.spinFilterSample2.setMaximum(1000)
        self.spinFilterSample2.setProperty("value", 5)
        self.spinFilterSample2.setObjectName("spinFilterSample2")
        self.gridLayout.addWidget(self.spinFilterSample2, 4, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.widgetFilter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 5, 0, 1, 1)
        self.cboParentSeqFilter = QtGui.QComboBox(self.widgetFilter)
        self.cboParentSeqFilter.setEnabled(False)
        self.cboParentSeqFilter.setObjectName("cboParentSeqFilter")
        self.cboParentSeqFilter.addItem("")
        self.cboParentSeqFilter.addItem("")
        self.cboParentSeqFilter.addItem("")
        self.gridLayout.addWidget(self.cboParentSeqFilter, 5, 1, 1, 1)
        self.chkEnableParentSeqFilter = QtGui.QCheckBox(self.widgetFilter)
        self.chkEnableParentSeqFilter.setChecked(False)
        self.chkEnableParentSeqFilter.setObjectName("chkEnableParentSeqFilter")
        self.gridLayout.addWidget(self.chkEnableParentSeqFilter, 5, 2, 1, 1)
        self.lblParentSeqFilterSample1 = QtGui.QLabel(self.widgetFilter)
        self.lblParentSeqFilterSample1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblParentSeqFilterSample1.setObjectName("lblParentSeqFilterSample1")
        self.gridLayout.addWidget(self.lblParentSeqFilterSample1, 6, 0, 1, 1)
        self.spinParentFilterSample1 = QtGui.QSpinBox(self.widgetFilter)
        self.spinParentFilterSample1.setEnabled(False)
        self.spinParentFilterSample1.setMaximum(10000)
        self.spinParentFilterSample1.setProperty("value", 1)
        self.spinParentFilterSample1.setObjectName("spinParentFilterSample1")
        self.gridLayout.addWidget(self.spinParentFilterSample1, 6, 1, 1, 1)
        self.lblParentSeqFilterSample2 = QtGui.QLabel(self.widgetFilter)
        self.lblParentSeqFilterSample2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblParentSeqFilterSample2.setObjectName("lblParentSeqFilterSample2")
        self.gridLayout.addWidget(self.lblParentSeqFilterSample2, 7, 0, 1, 1)
        self.spinParentFilterSample2 = QtGui.QSpinBox(self.widgetFilter)
        self.spinParentFilterSample2.setEnabled(False)
        self.spinParentFilterSample2.setMaximum(10000)
        self.spinParentFilterSample2.setProperty("value", 1)
        self.spinParentFilterSample2.setObjectName("spinParentFilterSample2")
        self.gridLayout.addWidget(self.spinParentFilterSample2, 7, 1, 1, 1)
        self.line_7 = QtGui.QFrame(self.widgetFilter)
        self.line_7.setFrameShadow(QtGui.QFrame.Plain)
        self.line_7.setMidLineWidth(0)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 8, 0, 1, 3)
        self.label_9 = QtGui.QLabel(self.widgetFilter)
        self.label_9.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 9, 0, 1, 1)
        self.cboEffectSizeMeasure1 = QtGui.QComboBox(self.widgetFilter)
        self.cboEffectSizeMeasure1.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboEffectSizeMeasure1.sizePolicy().hasHeightForWidth())
        self.cboEffectSizeMeasure1.setSizePolicy(sizePolicy)
        self.cboEffectSizeMeasure1.setObjectName("cboEffectSizeMeasure1")
        self.gridLayout.addWidget(self.cboEffectSizeMeasure1, 9, 1, 1, 1)
        self.chkEnableEffectSizeFilter1 = QtGui.QCheckBox(self.widgetFilter)
        self.chkEnableEffectSizeFilter1.setChecked(False)
        self.chkEnableEffectSizeFilter1.setObjectName("chkEnableEffectSizeFilter1")
        self.gridLayout.addWidget(self.chkEnableEffectSizeFilter1, 9, 2, 1, 1)
        self.lblMinEffectSize = QtGui.QLabel(self.widgetFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMinEffectSize.sizePolicy().hasHeightForWidth())
        self.lblMinEffectSize.setSizePolicy(sizePolicy)
        self.lblMinEffectSize.setMinimumSize(QtCore.QSize(0, 0))
        self.lblMinEffectSize.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblMinEffectSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblMinEffectSize.setObjectName("lblMinEffectSize")
        self.gridLayout.addWidget(self.lblMinEffectSize, 10, 0, 1, 1)
        self.spinMinEffectSize1 = QtGui.QDoubleSpinBox(self.widgetFilter)
        self.spinMinEffectSize1.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinMinEffectSize1.sizePolicy().hasHeightForWidth())
        self.spinMinEffectSize1.setSizePolicy(sizePolicy)
        self.spinMinEffectSize1.setMinimumSize(QtCore.QSize(0, 0))
        self.spinMinEffectSize1.setSingleStep(0.01)
        self.spinMinEffectSize1.setProperty("value", 1.0)
        self.spinMinEffectSize1.setObjectName("spinMinEffectSize1")
        self.gridLayout.addWidget(self.spinMinEffectSize1, 10, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.widgetFilter)
        self.label_17.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 12, 0, 1, 1)
        self.cboEffectSizeMeasure2 = QtGui.QComboBox(self.widgetFilter)
        self.cboEffectSizeMeasure2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboEffectSizeMeasure2.sizePolicy().hasHeightForWidth())
        self.cboEffectSizeMeasure2.setSizePolicy(sizePolicy)
        self.cboEffectSizeMeasure2.setObjectName("cboEffectSizeMeasure2")
        self.gridLayout.addWidget(self.cboEffectSizeMeasure2, 12, 1, 1, 1)
        self.chkEnableEffectSizeFilter2 = QtGui.QCheckBox(self.widgetFilter)
        self.chkEnableEffectSizeFilter2.setChecked(False)
        self.chkEnableEffectSizeFilter2.setObjectName("chkEnableEffectSizeFilter2")
        self.gridLayout.addWidget(self.chkEnableEffectSizeFilter2, 12, 2, 1, 1)
        self.lblMinEffectSize_2 = QtGui.QLabel(self.widgetFilter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMinEffectSize_2.sizePolicy().hasHeightForWidth())
        self.lblMinEffectSize_2.setSizePolicy(sizePolicy)
        self.lblMinEffectSize_2.setMinimumSize(QtCore.QSize(0, 0))
        self.lblMinEffectSize_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblMinEffectSize_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblMinEffectSize_2.setObjectName("lblMinEffectSize_2")
        self.gridLayout.addWidget(self.lblMinEffectSize_2, 13, 0, 1, 1)
        self.spinMinEffectSize2 = QtGui.QDoubleSpinBox(self.widgetFilter)
        self.spinMinEffectSize2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinMinEffectSize2.sizePolicy().hasHeightForWidth())
        self.spinMinEffectSize2.setSizePolicy(sizePolicy)
        self.spinMinEffectSize2.setMinimumSize(QtCore.QSize(0, 0))
        self.spinMinEffectSize2.setMinimum(0.0)
        self.spinMinEffectSize2.setSingleStep(0.01)
        self.spinMinEffectSize2.setProperty("value", 2.0)
        self.spinMinEffectSize2.setObjectName("spinMinEffectSize2")
        self.gridLayout.addWidget(self.spinMinEffectSize2, 13, 1, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem1)
        self.radioOR = QtGui.QRadioButton(self.widgetFilter)
        self.radioOR.setChecked(True)
        self.radioOR.setObjectName("radioOR")
        self.horizontalLayout_13.addWidget(self.radioOR)
        self.radioAND = QtGui.QRadioButton(self.widgetFilter)
        self.radioAND.setObjectName("radioAND")
        self.horizontalLayout_13.addWidget(self.radioAND)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_13, 11, 1, 1, 1)
        self.line_9 = QtGui.QFrame(self.widgetFilter)
        self.line_9.setFrameShadow(QtGui.QFrame.Plain)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout.addWidget(self.line_9, 1, 0, 1, 3)
        self.verticalLayout_13.addLayout(self.gridLayout)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.btnApplyFilters = QtGui.QPushButton(self.widgetFilter)
        self.btnApplyFilters.setIcon(icon3)
        self.btnApplyFilters.setObjectName("btnApplyFilters")
        self.horizontalLayout_24.addWidget(self.btnApplyFilters)
        self.verticalLayout_13.addLayout(self.horizontalLayout_24)
        self.line_8 = QtGui.QFrame(self.widgetFilter)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_13.addWidget(self.line_8)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_10 = QtGui.QLabel(self.widgetFilter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.txtNumActiveFeatures = QtGui.QLineEdit(self.widgetFilter)
        self.txtNumActiveFeatures.setReadOnly(True)
        self.txtNumActiveFeatures.setObjectName("txtNumActiveFeatures")
        self.horizontalLayout_3.addWidget(self.txtNumActiveFeatures)
        self.verticalLayout_13.addLayout(self.horizontalLayout_3)
        self.verticalLayout_12.addWidget(self.widgetFilter)
        self.verticalLayout.addWidget(self.groupFiltering)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.scrollArea.setWidget(self.scrollAreaSideBar)
        self.tabWidget = QtGui.QTabWidget(self.splitter)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tabExploratoryPlots = QtGui.QWidget()
        self.tabExploratoryPlots.setObjectName("tabExploratoryPlots")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabExploratoryPlots)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plotExploratoryScrollArea = QtGui.QScrollArea(self.tabExploratoryPlots)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.plotExploratoryScrollArea.setPalette(palette)
        self.plotExploratoryScrollArea.setAutoFillBackground(True)
        self.plotExploratoryScrollArea.setFrameShape(QtGui.QFrame.StyledPanel)
        self.plotExploratoryScrollArea.setFrameShadow(QtGui.QFrame.Plain)
        self.plotExploratoryScrollArea.setWidgetResizable(True)
        self.plotExploratoryScrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.plotExploratoryScrollArea.setObjectName("plotExploratoryScrollArea")
        self.scrollAreaWidgetContents_2 = QtGui.QWidget(self.plotExploratoryScrollArea)
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 666, 582))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.plotExploratoryScrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.addWidget(self.plotExploratoryScrollArea)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem4 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.cboExploratoryPlots = QtGui.QComboBox(self.tabExploratoryPlots)
        self.cboExploratoryPlots.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboExploratoryPlots.sizePolicy().hasHeightForWidth())
        self.cboExploratoryPlots.setSizePolicy(sizePolicy)
        self.cboExploratoryPlots.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.cboExploratoryPlots.setObjectName("cboExploratoryPlots")
        self.horizontalLayout_9.addWidget(self.cboExploratoryPlots)
        self.btnExploratoryConfigurePlot = QtGui.QPushButton(self.tabExploratoryPlots)
        self.btnExploratoryConfigurePlot.setEnabled(True)
        self.btnExploratoryConfigurePlot.setObjectName("btnExploratoryConfigurePlot")
        self.horizontalLayout_9.addWidget(self.btnExploratoryConfigurePlot)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_9)
        spacerItem5 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.label_16 = QtGui.QLabel(self.tabExploratoryPlots)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_8.addWidget(self.label_16)
        self.cboHighlightHierarchyExploratory = QtGui.QComboBox(self.tabExploratoryPlots)
        self.cboHighlightHierarchyExploratory.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.cboHighlightHierarchyExploratory.setObjectName("cboHighlightHierarchyExploratory")
        self.horizontalLayout_8.addWidget(self.cboHighlightHierarchyExploratory)
        self.cboHighlightFeatureExploratory = QtGui.QComboBox(self.tabExploratoryPlots)
        self.cboHighlightFeatureExploratory.setInsertPolicy(QtGui.QComboBox.InsertAtBottom)
        self.cboHighlightFeatureExploratory.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.cboHighlightFeatureExploratory.setObjectName("cboHighlightFeatureExploratory")
        self.horizontalLayout_8.addWidget(self.cboHighlightFeatureExploratory)
        spacerItem6 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.tabWidget.addTab(self.tabExploratoryPlots, "")
        self.tabStatisticalPlots = QtGui.QWidget()
        self.tabStatisticalPlots.setObjectName("tabStatisticalPlots")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tabStatisticalPlots)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.plotStatScrollArea = QtGui.QScrollArea(self.tabStatisticalPlots)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.plotStatScrollArea.setPalette(palette)
        self.plotStatScrollArea.setAutoFillBackground(True)
        self.plotStatScrollArea.setFrameShape(QtGui.QFrame.StyledPanel)
        self.plotStatScrollArea.setFrameShadow(QtGui.QFrame.Plain)
        self.plotStatScrollArea.setWidgetResizable(True)
        self.plotStatScrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.plotStatScrollArea.setObjectName("plotStatScrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget(self.plotStatScrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.plotStatScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_8.addWidget(self.plotStatScrollArea)
        self.statsPlotWidgetLayout = QtGui.QHBoxLayout()
        self.statsPlotWidgetLayout.setObjectName("statsPlotWidgetLayout")
        spacerItem7 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.statsPlotWidgetLayout.addItem(spacerItem7)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cboStatPlots = QtGui.QComboBox(self.tabStatisticalPlots)
        self.cboStatPlots.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboStatPlots.sizePolicy().hasHeightForWidth())
        self.cboStatPlots.setSizePolicy(sizePolicy)
        self.cboStatPlots.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.cboStatPlots.setObjectName("cboStatPlots")
        self.horizontalLayout.addWidget(self.cboStatPlots)
        self.btnStatConfigurePlot = QtGui.QPushButton(self.tabStatisticalPlots)
        self.btnStatConfigurePlot.setEnabled(True)
        self.btnStatConfigurePlot.setObjectName("btnStatConfigurePlot")
        self.horizontalLayout.addWidget(self.btnStatConfigurePlot)
        self.statsPlotWidgetLayout.addLayout(self.horizontalLayout)
        spacerItem8 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.statsPlotWidgetLayout.addItem(spacerItem8)
        self.label_13 = QtGui.QLabel(self.tabStatisticalPlots)
        self.label_13.setObjectName("label_13")
        self.statsPlotWidgetLayout.addWidget(self.label_13)
        self.cboHighlightHierarchyStats = QtGui.QComboBox(self.tabStatisticalPlots)
        self.cboHighlightHierarchyStats.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.cboHighlightHierarchyStats.setObjectName("cboHighlightHierarchyStats")
        self.statsPlotWidgetLayout.addWidget(self.cboHighlightHierarchyStats)
        self.cboHighlightFeatureStats = QtGui.QComboBox(self.tabStatisticalPlots)
        self.cboHighlightFeatureStats.setInsertPolicy(QtGui.QComboBox.InsertAtBottom)
        self.cboHighlightFeatureStats.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.cboHighlightFeatureStats.setObjectName("cboHighlightFeatureStats")
        self.statsPlotWidgetLayout.addWidget(self.cboHighlightFeatureStats)
        spacerItem9 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.statsPlotWidgetLayout.addItem(spacerItem9)
        self.verticalLayout_8.addLayout(self.statsPlotWidgetLayout)
        self.tabWidget.addTab(self.tabStatisticalPlots, "")
        self.tabSummaryTable = QtGui.QWidget()
        self.tabSummaryTable.setObjectName("tabSummaryTable")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabSummaryTable)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableSummary = QtGui.QTableView(self.tabSummaryTable)
        self.tableSummary.setAlternatingRowColors(True)
        self.tableSummary.setShowGrid(True)
        self.tableSummary.setSortingEnabled(True)
        self.tableSummary.setObjectName("tableSummary")
        self.verticalLayout_3.addWidget(self.tableSummary)
        self.chkShowActiveFeatures = QtGui.QCheckBox(self.tabSummaryTable)
        self.chkShowActiveFeatures.setChecked(True)
        self.chkShowActiveFeatures.setObjectName("chkShowActiveFeatures")
        self.verticalLayout_3.addWidget(self.chkShowActiveFeatures)
        self.tabWidget.addTab(self.tabSummaryTable, "")
        self.tabConfIntervCoverage = QtGui.QWidget()
        self.tabConfIntervCoverage.setObjectName("tabConfIntervCoverage")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.tabConfIntervCoverage)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lblCoverageTableTitle = QtGui.QLabel(self.tabConfIntervCoverage)
        self.lblCoverageTableTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCoverageTableTitle.setObjectName("lblCoverageTableTitle")
        self.verticalLayout_10.addWidget(self.lblCoverageTableTitle)
        self.tableConfInterCoverage = QtGui.QTableView(self.tabConfIntervCoverage)
        self.tableConfInterCoverage.setAlternatingRowColors(True)
        self.tableConfInterCoverage.setShowGrid(True)
        self.tableConfInterCoverage.setSortingEnabled(True)
        self.tableConfInterCoverage.setObjectName("tableConfInterCoverage")
        self.verticalLayout_10.addWidget(self.tableConfInterCoverage)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.chkConfInterActiveFeature = QtGui.QCheckBox(self.tabConfIntervCoverage)
        self.chkConfInterActiveFeature.setChecked(True)
        self.chkConfInterActiveFeature.setObjectName("chkConfInterActiveFeature")
        self.horizontalLayout_17.addWidget(self.chkConfInterActiveFeature)
        spacerItem10 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem10)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtGui.QLabel(self.tabConfIntervCoverage)
        self.label_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.cboCoverage = QtGui.QComboBox(self.tabConfIntervCoverage)
        self.cboCoverage.setObjectName("cboCoverage")
        self.cboCoverage.addItem("")
        self.cboCoverage.addItem("")
        self.cboCoverage.addItem("")
        self.cboCoverage.addItem("")
        self.cboCoverage.addItem("")
        self.cboCoverage.addItem("")
        self.cboCoverage.addItem("")
        self.cboCoverage.addItem("")
        self.horizontalLayout_5.addWidget(self.cboCoverage)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_2 = QtGui.QLabel(self.tabConfIntervCoverage)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_10.addWidget(self.label_2)
        self.spinConfIntervTrials = QtGui.QSpinBox(self.tabConfIntervCoverage)
        self.spinConfIntervTrials.setMinimum(1)
        self.spinConfIntervTrials.setMaximum(100)
        self.spinConfIntervTrials.setProperty("value", 4)
        self.spinConfIntervTrials.setObjectName("spinConfIntervTrials")
        self.horizontalLayout_10.addWidget(self.spinConfIntervTrials)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label = QtGui.QLabel(self.tabConfIntervCoverage)
        self.label.setObjectName("label")
        self.horizontalLayout_11.addWidget(self.label)
        self.spinConfIntervReplicates = QtGui.QSpinBox(self.tabConfIntervCoverage)
        self.spinConfIntervReplicates.setMinimum(1)
        self.spinConfIntervReplicates.setMaximum(100000)
        self.spinConfIntervReplicates.setSingleStep(100)
        self.spinConfIntervReplicates.setProperty("value", 100)
        self.spinConfIntervReplicates.setObjectName("spinConfIntervReplicates")
        self.horizontalLayout_11.addWidget(self.spinConfIntervReplicates)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_11)
        self.btnConfIntervCoverage = QtGui.QPushButton(self.tabConfIntervCoverage)
        self.btnConfIntervCoverage.setObjectName("btnConfIntervCoverage")
        self.horizontalLayout_17.addWidget(self.btnConfIntervCoverage)
        self.verticalLayout_10.addLayout(self.horizontalLayout_17)
        self.tabWidget.addTab(self.tabConfIntervCoverage, "")
        self.tabPowerTest = QtGui.QWidget()
        self.tabPowerTest.setObjectName("tabPowerTest")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.tabPowerTest)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.lblPowerTestTitle = QtGui.QLabel(self.tabPowerTest)
        self.lblPowerTestTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPowerTestTitle.setObjectName("lblPowerTestTitle")
        self.verticalLayout_9.addWidget(self.lblPowerTestTitle)
        self.tablePower = QtGui.QTableView(self.tabPowerTest)
        self.tablePower.setAlternatingRowColors(True)
        self.tablePower.setShowGrid(True)
        self.tablePower.setSortingEnabled(True)
        self.tablePower.setObjectName("tablePower")
        self.verticalLayout_9.addWidget(self.tablePower)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.chkPowerActiveFeature = QtGui.QCheckBox(self.tabPowerTest)
        self.chkPowerActiveFeature.setChecked(True)
        self.chkPowerActiveFeature.setObjectName("chkPowerActiveFeature")
        self.horizontalLayout_16.addWidget(self.chkPowerActiveFeature)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem11)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtGui.QLabel(self.tabPowerTest)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.cboPowerSignLevel = QtGui.QComboBox(self.tabPowerTest)
        self.cboPowerSignLevel.setObjectName("cboPowerSignLevel")
        self.cboPowerSignLevel.addItem("")
        self.cboPowerSignLevel.addItem("")
        self.cboPowerSignLevel.addItem("")
        self.cboPowerSignLevel.addItem("")
        self.cboPowerSignLevel.addItem("")
        self.cboPowerSignLevel.addItem("")
        self.cboPowerSignLevel.addItem("")
        self.horizontalLayout_6.addWidget(self.cboPowerSignLevel)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_3 = QtGui.QLabel(self.tabPowerTest)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_14.addWidget(self.label_3)
        self.spinPowerTrials = QtGui.QSpinBox(self.tabPowerTest)
        self.spinPowerTrials.setMinimum(1)
        self.spinPowerTrials.setMaximum(100)
        self.spinPowerTrials.setProperty("value", 4)
        self.spinPowerTrials.setObjectName("spinPowerTrials")
        self.horizontalLayout_14.addWidget(self.spinPowerTrials)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_4 = QtGui.QLabel(self.tabPowerTest)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_15.addWidget(self.label_4)
        self.spinPowerReplicates = QtGui.QSpinBox(self.tabPowerTest)
        self.spinPowerReplicates.setMinimum(1)
        self.spinPowerReplicates.setMaximum(100000)
        self.spinPowerReplicates.setProperty("value", 100)
        self.spinPowerReplicates.setObjectName("spinPowerReplicates")
        self.horizontalLayout_15.addWidget(self.spinPowerReplicates)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_15)
        self.btnPowerTest = QtGui.QPushButton(self.tabPowerTest)
        self.btnPowerTest.setObjectName("btnPowerTest")
        self.horizontalLayout_16.addWidget(self.btnPowerTest)
        self.verticalLayout_9.addLayout(self.horizontalLayout_16)
        self.tabWidget.addTab(self.tabPowerTest, "")
        self.verticalLayout_7.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1103, 21))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        self.menu_View = QtGui.QMenu(self.menubar)
        self.menu_View.setObjectName("menu_View")
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.mnuFileExit = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mnuFileExit.setIcon(icon4)
        self.mnuFileExit.setObjectName("mnuFileExit")
        self.mnuHelpAbout = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mnuHelpAbout.setIcon(icon5)
        self.mnuHelpAbout.setObjectName("mnuHelpAbout")
        self.mnuFileSavePlot = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mnuFileSavePlot.setIcon(icon6)
        self.mnuFileSavePlot.setObjectName("mnuFileSavePlot")
        self.mnuFileSaveTable = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/saveas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mnuFileSaveTable.setIcon(icon7)
        self.mnuFileSaveTable.setObjectName("mnuFileSaveTable")
        self.mnuFileOpenProfile = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mnuFileOpenProfile.setIcon(icon8)
        self.mnuFileOpenProfile.setObjectName("mnuFileOpenProfile")
        self.mnuViewSendPlotToWindow = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/newwin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mnuViewSendPlotToWindow.setIcon(icon9)
        self.mnuViewSendPlotToWindow.setObjectName("mnuViewSendPlotToWindow")
        self.mnuSettingsPreferences = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icons/pref.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mnuSettingsPreferences.setIcon(icon10)
        self.mnuSettingsPreferences.setObjectName("mnuSettingsPreferences")
        self.mnuFileCreateProfile = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("icons/createProfile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mnuFileCreateProfile.setIcon(icon11)
        self.mnuFileCreateProfile.setObjectName("mnuFileCreateProfile")
        self.mnuFileAppendCategoryCOG = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("icons/appendCOGs.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mnuFileAppendCategoryCOG.setIcon(icon12)
        self.mnuFileAppendCategoryCOG.setObjectName("mnuFileAppendCategoryCOG")
        self.menu_File.addAction(self.mnuFileOpenProfile)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.mnuFileCreateProfile)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.mnuFileAppendCategoryCOG)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.mnuFileSavePlot)
        self.menu_File.addAction(self.mnuFileSaveTable)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.mnuFileExit)
        self.menu_Help.addAction(self.mnuHelpAbout)
        self.menu_View.addAction(self.mnuViewSendPlotToWindow)
        self.menuSettings.addAction(self.mnuSettingsPreferences)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.cboSignTestType.setCurrentIndex(1)
        self.cboNominalCoverage.setCurrentIndex(1)
        self.cboParentSeqFilter.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.cboCoverage.setCurrentIndex(1)
        self.cboPowerSignLevel.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.scrollArea, self.btnProfileArrow)
        MainWindow.setTabOrder(self.btnProfileArrow, self.btnProfileTab)
        MainWindow.setTabOrder(self.btnProfileTab, self.cboSample1)
        MainWindow.setTabOrder(self.cboSample1, self.btnSample1Colour)
        MainWindow.setTabOrder(self.btnSample1Colour, self.cboSample2)
        MainWindow.setTabOrder(self.cboSample2, self.btnSample2Colour)
        MainWindow.setTabOrder(self.btnSample2Colour, self.cboParentalLevel)
        MainWindow.setTabOrder(self.cboParentalLevel, self.cboProfileLevel)
        MainWindow.setTabOrder(self.cboProfileLevel, self.txtNumParentCategories)
        MainWindow.setTabOrder(self.txtNumParentCategories, self.txtNumFeatures)
        MainWindow.setTabOrder(self.txtNumFeatures, self.txtTotalSeqs1)
        MainWindow.setTabOrder(self.txtTotalSeqs1, self.txtTotalSeqs2)
        MainWindow.setTabOrder(self.txtTotalSeqs2, self.btnStatisticsArrow)
        MainWindow.setTabOrder(self.btnStatisticsArrow, self.btnStatisticsTab)
        MainWindow.setTabOrder(self.btnStatisticsTab, self.cboStatTests)
        MainWindow.setTabOrder(self.cboStatTests, self.cboSignTestType)
        MainWindow.setTabOrder(self.cboSignTestType, self.cboConfIntervMethods)
        MainWindow.setTabOrder(self.cboConfIntervMethods, self.cboNominalCoverage)
        MainWindow.setTabOrder(self.cboNominalCoverage, self.btnRunTest)
        MainWindow.setTabOrder(self.btnRunTest, self.btnFilteringArrow)
        MainWindow.setTabOrder(self.btnFilteringArrow, self.btnFilteringTab)
        MainWindow.setTabOrder(self.btnFilteringTab, self.spinSignLevelFilter)
        MainWindow.setTabOrder(self.spinSignLevelFilter, self.chkEnableSignLevelFilter)
        MainWindow.setTabOrder(self.chkEnableSignLevelFilter, self.cboSeqFilter)
        MainWindow.setTabOrder(self.cboSeqFilter, self.chkEnableSeqFilter)
        MainWindow.setTabOrder(self.chkEnableSeqFilter, self.spinFilterSample1)
        MainWindow.setTabOrder(self.spinFilterSample1, self.spinFilterSample2)
        MainWindow.setTabOrder(self.spinFilterSample2, self.cboParentSeqFilter)
        MainWindow.setTabOrder(self.cboParentSeqFilter, self.chkEnableParentSeqFilter)
        MainWindow.setTabOrder(self.chkEnableParentSeqFilter, self.spinParentFilterSample1)
        MainWindow.setTabOrder(self.spinParentFilterSample1, self.spinParentFilterSample2)
        MainWindow.setTabOrder(self.spinParentFilterSample2, self.cboEffectSizeMeasure1)
        MainWindow.setTabOrder(self.cboEffectSizeMeasure1, self.chkEnableEffectSizeFilter1)
        MainWindow.setTabOrder(self.chkEnableEffectSizeFilter1, self.spinMinEffectSize1)
        MainWindow.setTabOrder(self.spinMinEffectSize1, self.cboEffectSizeMeasure2)
        MainWindow.setTabOrder(self.cboEffectSizeMeasure2, self.chkEnableEffectSizeFilter2)
        MainWindow.setTabOrder(self.chkEnableEffectSizeFilter2, self.spinMinEffectSize2)
        MainWindow.setTabOrder(self.spinMinEffectSize2, self.radioOR)
        MainWindow.setTabOrder(self.radioOR, self.radioAND)
        MainWindow.setTabOrder(self.radioAND, self.btnApplyFilters)
        MainWindow.setTabOrder(self.btnApplyFilters, self.chkSelectFeatures)
        MainWindow.setTabOrder(self.chkSelectFeatures, self.btnSelectFeatures)
        MainWindow.setTabOrder(self.btnSelectFeatures, self.txtNumActiveFeatures)
        MainWindow.setTabOrder(self.txtNumActiveFeatures, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.plotExploratoryScrollArea)
        MainWindow.setTabOrder(self.plotExploratoryScrollArea, self.cboExploratoryPlots)
        MainWindow.setTabOrder(self.cboExploratoryPlots, self.btnExploratoryConfigurePlot)
        MainWindow.setTabOrder(self.btnExploratoryConfigurePlot, self.cboHighlightHierarchyExploratory)
        MainWindow.setTabOrder(self.cboHighlightHierarchyExploratory, self.cboHighlightFeatureExploratory)
        MainWindow.setTabOrder(self.cboHighlightFeatureExploratory, self.plotStatScrollArea)
        MainWindow.setTabOrder(self.plotStatScrollArea, self.cboStatPlots)
        MainWindow.setTabOrder(self.cboStatPlots, self.btnStatConfigurePlot)
        MainWindow.setTabOrder(self.btnStatConfigurePlot, self.cboHighlightHierarchyStats)
        MainWindow.setTabOrder(self.cboHighlightHierarchyStats, self.cboHighlightFeatureStats)
        MainWindow.setTabOrder(self.cboHighlightFeatureStats, self.tableSummary)
        MainWindow.setTabOrder(self.tableSummary, self.chkShowActiveFeatures)
        MainWindow.setTabOrder(self.chkShowActiveFeatures, self.tableConfInterCoverage)
        MainWindow.setTabOrder(self.tableConfInterCoverage, self.chkConfInterActiveFeature)
        MainWindow.setTabOrder(self.chkConfInterActiveFeature, self.cboCoverage)
        MainWindow.setTabOrder(self.cboCoverage, self.spinConfIntervTrials)
        MainWindow.setTabOrder(self.spinConfIntervTrials, self.spinConfIntervReplicates)
        MainWindow.setTabOrder(self.spinConfIntervReplicates, self.btnConfIntervCoverage)
        MainWindow.setTabOrder(self.btnConfIntervCoverage, self.tablePower)
        MainWindow.setTabOrder(self.tablePower, self.chkPowerActiveFeature)
        MainWindow.setTabOrder(self.chkPowerActiveFeature, self.cboPowerSignLevel)
        MainWindow.setTabOrder(self.cboPowerSignLevel, self.spinPowerTrials)
        MainWindow.setTabOrder(self.spinPowerTrials, self.spinPowerReplicates)
        MainWindow.setTabOrder(self.spinPowerReplicates, self.btnPowerTest)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "STAMP - Statistical analysis of metagenomic profiles", None, QtGui.QApplication.UnicodeUTF8))
        self.btnProfileTab.setText(QtGui.QApplication.translate("MainWindow", "Profile", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Sample 1:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Sample 2:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Parent level:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProfile.setText(QtGui.QApplication.translate("MainWindow", "Profile level:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblParentCategories.setText(QtGui.QApplication.translate("MainWindow", "Parent categories:", None, QtGui.QApplication.UnicodeUTF8))
        self.txtNumParentCategories.setStyleSheet(QtGui.QApplication.translate("MainWindow", "background-color: rgb(255, 255, 235);", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFeatures.setText(QtGui.QApplication.translate("MainWindow", "Features:", None, QtGui.QApplication.UnicodeUTF8))
        self.txtNumFeatures.setStyleSheet(QtGui.QApplication.translate("MainWindow", "background-color: rgb(255, 255, 235);", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTotalSeqs.setText(QtGui.QApplication.translate("MainWindow", "Total sequences:", None, QtGui.QApplication.UnicodeUTF8))
        self.txtTotalSeqs1.setStyleSheet(QtGui.QApplication.translate("MainWindow", "background-color: rgb(255, 255, 235);", None, QtGui.QApplication.UnicodeUTF8))
        self.txtTotalSeqs2.setStyleSheet(QtGui.QApplication.translate("MainWindow", "background-color: rgb(255, 255, 235);", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStatisticsTab.setText(QtGui.QApplication.translate("MainWindow", "Statistical properties", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStatisticalTest.setText(QtGui.QApplication.translate("MainWindow", "Statistical test:", None, QtGui.QApplication.UnicodeUTF8))
        self.cboStatTests.setStatusTip(QtGui.QApplication.translate("MainWindow", "Set statistical test to perform", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.cboSignTestType.setItemText(0, QtGui.QApplication.translate("MainWindow", "One sided", None, QtGui.QApplication.UnicodeUTF8))
        self.cboSignTestType.setItemText(1, QtGui.QApplication.translate("MainWindow", "Two sided", None, QtGui.QApplication.UnicodeUTF8))
        self.lblConfidenceIntervalMethod.setText(QtGui.QApplication.translate("MainWindow", "CI method:", None, QtGui.QApplication.UnicodeUTF8))
        self.cboNominalCoverage.setStatusTip(QtGui.QApplication.translate("MainWindow", "Set level of significance", None, QtGui.QApplication.UnicodeUTF8))
        self.cboNominalCoverage.setItemText(0, QtGui.QApplication.translate("MainWindow", "0.90", None, QtGui.QApplication.UnicodeUTF8))
        self.cboNominalCoverage.setItemText(1, QtGui.QApplication.translate("MainWindow", "0.95", None, QtGui.QApplication.UnicodeUTF8))
        self.cboNominalCoverage.setItemText(2, QtGui.QApplication.translate("MainWindow", "0.98", None, QtGui.QApplication.UnicodeUTF8))
        self.cboNominalCoverage.setItemText(3, QtGui.QApplication.translate("MainWindow", "0.99", None, QtGui.QApplication.UnicodeUTF8))
        self.cboNominalCoverage.setItemText(4, QtGui.QApplication.translate("MainWindow", "0.999", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Multiple test correction:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRunTest.setText(QtGui.QApplication.translate("MainWindow", "Perform statistical analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFilteringTab.setText(QtGui.QApplication.translate("MainWindow", "Filtering", None, QtGui.QApplication.UnicodeUTF8))
        self.chkSelectFeatures.setText(QtGui.QApplication.translate("MainWindow", "Select specific features", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSelectFeatures.setText(QtGui.QApplication.translate("MainWindow", "Select features", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSignLevelFilter.setText(QtGui.QApplication.translate("MainWindow", "p-value filter (>):", None, QtGui.QApplication.UnicodeUTF8))
        self.spinSignLevelFilter.setStatusTip(QtGui.QApplication.translate("MainWindow", "Filter out feature with an effect size less than the specified amount", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSeqFilter.setText(QtGui.QApplication.translate("MainWindow", "Sequence filter:", None, QtGui.QApplication.UnicodeUTF8))
        self.cboSeqFilter.setItemText(0, QtGui.QApplication.translate("MainWindow", "maximum", None, QtGui.QApplication.UnicodeUTF8))
        self.cboSeqFilter.setItemText(1, QtGui.QApplication.translate("MainWindow", "minimum", None, QtGui.QApplication.UnicodeUTF8))
        self.cboSeqFilter.setItemText(2, QtGui.QApplication.translate("MainWindow", "independent", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSeqFilterSample1.setText(QtGui.QApplication.translate("MainWindow", "Sample 1 (<):", None, QtGui.QApplication.UnicodeUTF8))
        self.spinFilterSample1.setStatusTip(QtGui.QApplication.translate("MainWindow", "Filter out all features where sample 2 does not contain more than the specified number of sequences", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSeqFilterSample2.setText(QtGui.QApplication.translate("MainWindow", "Sample 2 (<):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Parent seq. filter:", None, QtGui.QApplication.UnicodeUTF8))
        self.cboParentSeqFilter.setItemText(0, QtGui.QApplication.translate("MainWindow", "maximum", None, QtGui.QApplication.UnicodeUTF8))
        self.cboParentSeqFilter.setItemText(1, QtGui.QApplication.translate("MainWindow", "minimum", None, QtGui.QApplication.UnicodeUTF8))
        self.cboParentSeqFilter.setItemText(2, QtGui.QApplication.translate("MainWindow", "independent", None, QtGui.QApplication.UnicodeUTF8))
        self.lblParentSeqFilterSample1.setText(QtGui.QApplication.translate("MainWindow", "Sample1 (<):", None, QtGui.QApplication.UnicodeUTF8))
        self.lblParentSeqFilterSample2.setText(QtGui.QApplication.translate("MainWindow", "Sample 2 (<):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Effect size filter 1:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMinEffectSize.setText(QtGui.QApplication.translate("MainWindow", "Effect size (<):", None, QtGui.QApplication.UnicodeUTF8))
        self.spinMinEffectSize1.setStatusTip(QtGui.QApplication.translate("MainWindow", "Filter out feature with an effect size less than the specified amount", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Effect size filter 2:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMinEffectSize_2.setText(QtGui.QApplication.translate("MainWindow", "Effect size (<):", None, QtGui.QApplication.UnicodeUTF8))
        self.spinMinEffectSize2.setStatusTip(QtGui.QApplication.translate("MainWindow", "Filter out feature with an effect size less than the specified amount", None, QtGui.QApplication.UnicodeUTF8))
        self.radioOR.setText(QtGui.QApplication.translate("MainWindow", "OR", None, QtGui.QApplication.UnicodeUTF8))
        self.radioAND.setText(QtGui.QApplication.translate("MainWindow", "AND", None, QtGui.QApplication.UnicodeUTF8))
        self.btnApplyFilters.setText(QtGui.QApplication.translate("MainWindow", "Perform filtering", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Number active features:", None, QtGui.QApplication.UnicodeUTF8))
        self.txtNumActiveFeatures.setStyleSheet(QtGui.QApplication.translate("MainWindow", "background-color: rgb(255, 255, 235);", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExploratoryConfigurePlot.setText(QtGui.QApplication.translate("MainWindow", "Configure plot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Highlight:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabExploratoryPlots), QtGui.QApplication.translate("MainWindow", "Exploratory plots", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStatConfigurePlot.setText(QtGui.QApplication.translate("MainWindow", "Configure plot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Highlight:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStatisticalPlots), QtGui.QApplication.translate("MainWindow", "Statistical plots", None, QtGui.QApplication.UnicodeUTF8))
        self.chkShowActiveFeatures.setText(QtGui.QApplication.translate("MainWindow", "Show only active features", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSummaryTable), QtGui.QApplication.translate("MainWindow", "Statistical results table", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCoverageTableTitle.setText(QtGui.QApplication.translate("MainWindow", "Confidence Interval Coverage", None, QtGui.QApplication.UnicodeUTF8))
        self.chkConfInterActiveFeature.setText(QtGui.QApplication.translate("MainWindow", "Consider only active features", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Coverage:", None, QtGui.QApplication.UnicodeUTF8))
        self.cboCoverage.setItemText(0, QtGui.QApplication.translate("MainWindow", "90", None, QtGui.QApplication.UnicodeUTF8))
        self.cboCoverage.setItemText(1, QtGui.QApplication.translate("MainWindow", "95", None, QtGui.QApplication.UnicodeUTF8))
        self.cboCoverage.setItemText(2, QtGui.QApplication.translate("MainWindow", "98", None, QtGui.QApplication.UnicodeUTF8))
        self.cboCoverage.setItemText(3, QtGui.QApplication.translate("MainWindow", "99", None, QtGui.QApplication.UnicodeUTF8))
        self.cboCoverage.setItemText(4, QtGui.QApplication.translate("MainWindow", "99.9", None, QtGui.QApplication.UnicodeUTF8))
        self.cboCoverage.setItemText(5, QtGui.QApplication.translate("MainWindow", "99.99", None, QtGui.QApplication.UnicodeUTF8))
        self.cboCoverage.setItemText(6, QtGui.QApplication.translate("MainWindow", "99.999", None, QtGui.QApplication.UnicodeUTF8))
        self.cboCoverage.setItemText(7, QtGui.QApplication.translate("MainWindow", "99.9999", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Trials:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Bootstrap replicates:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnConfIntervCoverage.setText(QtGui.QApplication.translate("MainWindow", "Calculate coverage", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabConfIntervCoverage), QtGui.QApplication.translate("MainWindow", "CI coverage", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPowerTestTitle.setText(QtGui.QApplication.translate("MainWindow", "Power Test", None, QtGui.QApplication.UnicodeUTF8))
        self.chkPowerActiveFeature.setText(QtGui.QApplication.translate("MainWindow", "Consider only active features", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Significance level:", None, QtGui.QApplication.UnicodeUTF8))
        self.cboPowerSignLevel.setItemText(0, QtGui.QApplication.translate("MainWindow", "0.10", None, QtGui.QApplication.UnicodeUTF8))
        self.cboPowerSignLevel.setItemText(1, QtGui.QApplication.translate("MainWindow", "0.05", None, QtGui.QApplication.UnicodeUTF8))
        self.cboPowerSignLevel.setItemText(2, QtGui.QApplication.translate("MainWindow", "0.02", None, QtGui.QApplication.UnicodeUTF8))
        self.cboPowerSignLevel.setItemText(3, QtGui.QApplication.translate("MainWindow", "0.01", None, QtGui.QApplication.UnicodeUTF8))
        self.cboPowerSignLevel.setItemText(4, QtGui.QApplication.translate("MainWindow", "1e-3", None, QtGui.QApplication.UnicodeUTF8))
        self.cboPowerSignLevel.setItemText(5, QtGui.QApplication.translate("MainWindow", "1e-4", None, QtGui.QApplication.UnicodeUTF8))
        self.cboPowerSignLevel.setItemText(6, QtGui.QApplication.translate("MainWindow", "1e-5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Trials:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Bootstrap replicates:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPowerTest.setText(QtGui.QApplication.translate("MainWindow", "Calculate power", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPowerTest), QtGui.QApplication.translate("MainWindow", "Power test", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_View.setTitle(QtGui.QApplication.translate("MainWindow", "&View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSettings.setTitle(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuFileExit.setText(QtGui.QApplication.translate("MainWindow", "E&xit", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuFileExit.setStatusTip(QtGui.QApplication.translate("MainWindow", "Exit application", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuFileExit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuHelpAbout.setText(QtGui.QApplication.translate("MainWindow", "&About...", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuHelpAbout.setStatusTip(QtGui.QApplication.translate("MainWindow", "Show program information", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuFileSavePlot.setText(QtGui.QApplication.translate("MainWindow", "Save plot...", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuFileSavePlot.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuFileSaveTable.setText(QtGui.QApplication.translate("MainWindow", "Save table...", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuFileOpenProfile.setText(QtGui.QApplication.translate("MainWindow", "Open profiles...", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuFileOpenProfile.setToolTip(QtGui.QApplication.translate("MainWindow", "Load file containing metagenomic profiles", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuViewSendPlotToWindow.setText(QtGui.QApplication.translate("MainWindow", "Send &plot to window", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuViewSendPlotToWindow.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+W", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuSettingsPreferences.setText(QtGui.QApplication.translate("MainWindow", "Preferences...", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuFileCreateProfile.setText(QtGui.QApplication.translate("MainWindow", "Create profile from an MG-RAST table...", None, QtGui.QApplication.UnicodeUTF8))
        self.mnuFileAppendCategoryCOG.setText(QtGui.QApplication.translate("MainWindow", "Assign COG categories to an IMG/M profile...", None, QtGui.QApplication.UnicodeUTF8))

